<?php 
/**
 *
 * This is the footer.php file for the CRM Press theme.
 * DO NOT EDIT THIS FILE! IT WILL BE OVERRIDEN WITH FUTURE UPDATES.
 * If you wish to make customizations, please make a child theme instead.
 *
 */