<?php 
/**
 *
 * This is the header.php file for the CRM Press theme.
 * DO NOT EDIT THIS FILE! IT WILL BE OVERRIDEN WITH FUTURE UPDATES.
 * If you wish to make customizations, please make a child theme instead.
 *
 */

do_action( 'crmpress_head_doctype' );
do_action( 'crmpress_title' );
do_action( 'crmpress_link_tags' );
wp_head();

?>
</head>
<?php

do_action( 'crmpress_before_wireframe' );
do_action( 'crmpress_before_header' );
do_action( 'crmpress_header' );
do_action( 'crmpress_after_header' );