<?php 
/**
 *
 * This is the footer.php file for the CRM Press theme.
 * DO NOT EDIT THIS FILE! IT WILL BE OVERRIDEN WITH FUTURE UPDATES.
 * If you wish to make customizations, please make a child theme instead.
 *
 */

do_action( 'crmpress_before_footer' );
do_action( 'crmpress_footer' );
do_action( 'crmpress_after_footer' );
do_action( 'crmpress_after_wireframe' );
?>

</html>