<?php
/**
 *
 * This is the functions.php file for the inLine WordPress theme.
 * DO NOT EDIT THIS FILE! IT WILL BE OVERRIDEN WITH FUTURE UPDATES.
 * If you need to edit the core theme, please make a child theme instead.
 *
 */

require_once( dirname( __FILE__ ) . '/lib/init.php' );