<?php 
/**
 *
 * This is the home.php file for the CRM Press theme.
 * DO NOT EDIT THIS FILE! IT WILL BE OVERRIDEN WITH FUTURE UPDATES.
 * If you wish to make customizations, please make a child theme instead.
 *
 */

remove_action( 'crmpress_content', 'crmpress_do_content' );
add_action( 'crmpress_content', 'crmpress_home_loop' );
add_action( 'crmpress_content', 'crmpress_home_widgets' );

crmpress();