<?php 
/**
 *
 * This is the theme.php file for the CRM Press theme.
 * DO NOT EDIT THIS FILE! IT WILL BE OVERRIDEN WITH FUTURE UPDATES.
 * If you wish to make customizations, please make a child theme instead.
 *
 */

function crmpress() {
	
	global $prefix; // Add our global variable here so we don't have to call it anywhere else in our theme :)

	get_header();

	do_action( 'crmpress_top_section' );
	do_action( 'crmpress_before_main_content' ); // Adds a hook before the #main-content div
	do_action( 'crmpress_content' );
	do_action( 'crmpress_after_main_content' );

	get_footer();

}